/**
 * Created by Anoxic on 12/31/2017.
 *
 * A list of controls
 */

const ControlTypes = {
  NONE: "NONE",

  CONTROL_ROTATE: "CONTROL_ROTATE",
  CONTROL_UP    : "CONTROL_UP",
  CONTROL_DOWN  : "CONTROL_DOWN",
  CONTROL_LEFT  : "CONTROL_LEFT",
  CONTROL_RIGHT : "CONTROL_RIGHT",
  CONTROL_UNDO  : "CONTROL_UNDO",
  CONTROL_REDO  : "CONTROL_REDO",
  CONTROL_DONE  : "CONTROL_DONE",

  // Level editor
  CONTROL_TOGGLE_EDIT   : "CONTROL_TOGGLE_EDIT",
  CONTROL_PREV_DETROMINO: "CONTROL_PREV_DETROMINO",
  CONTROL_NEXT_DETROMINO: "CONTROL_NEXT_DETROMINO",
  CONTROL_BLOCK_SELECTOR: "CONTROL_BLOCK_SELECTOR",
};

export default ControlTypes;
