/**
 * Created by Anoxic on 1/15/2018.
 */

const DialogType = {
  START_TUTORIAL      : "START_TUTORIAL",
  GAME_RESTART        : "GAME_RESTART",
  RESET_LEVEL_EDITOR  : "RESET_LEVEL_EDITOR",
  QUIT_TO_SELECT_LEVEL: "QUIT_TO_SELECT_LEVEL",
  QUIT_TO_WELCOME     : "QUIT_TO_WELCOME",
  SKIP_TUTORIAL       : "SKIP_TUTORIAL",
  END_TUTORIAL        : "END_TUTORIAL",
};

export default DialogType;